### ISSUE TITLE
Cross Site Scripting

### ISSUE THREAD

**Issue by PPPio** [taogogo/taocms#2]
First
Enter the page: `http://127.0.0.1/taocms/admin/admin.php?action=frame&ctrl=iframes`
and the payload is:
<img width="986" alt="taocmsxss1-1" src="https://user-images.githubusercontent.com/41558659/66716536-592cd880-ee01-11e9-8eea-0a5dfc8e3411.png">
Then,we can see the result.
<img width="1060" alt="taocmsxss1-2" src="https://user-images.githubusercontent.com/41558659/66716545-6ea20280-ee01-11e9-8597-220aa7ddf725.png">

**Comment by taogogo** [comment]
3.0.1 fixed, thanks for your contribution
